<?php if(App::config('dev')):?>
<h1>You have searched for <?=$missingcontent?></h1>
<ul>
    <li>
        Controller class and method does not exist!
    </li>
    <li>
        Controller class or method might have a different name!!
    </li>
    <li>
        Your route might be wrong all together!!!
    </li>
</ul>
<?php else:?>
    <div class="grid-x grid-padding-x" style="text-align: center">
        <div class="large-12 cell">
            <h1>It seams you got lost!!</h1></br>
            <img src="<?=App::config('url')?>public/img/map.webp" alt="MiddleEarth">
            <h3>Return to Gandalf and ask him the way to <?=$missingcontent?>!!!</h3></br>
            <h3><a href="<?=App::config('url')?>">Gandalf</a></h3>
        </div>
    </div>    
<?php endif;?>