<form class="log-in-form"
action="<?=App::config('url')?>login/authorize"
method="POST">
  <h4 class="text-center">Authorization</h4>
  <label>Email
    <input type="username" name="username" value="<?=$username?>" />
  </label>
  <label>Password
    <input type="password" name="password" />
  </label>
  <p>
    <input type="submit" class="button expanded" value="Login" />
  </p>
  <ul>
      <li><?=$message?></li>
  </ul> 
</form>


