
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'templates/head.phtml' ?>
  </head>
<body>
    <?php include_once 'templates/menu.phtml' ?>

    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
            <div class="callout" id="program">
                <?=$content?>
            </div>
        </div>
      </div>
    </div>
    <div id="git">  
      <a href="https://github.com/mbozic987/ZavrsniRadPP24">
      <i class="fab fa-github-square"></i> github.com/mbozic987/ZavrsniRadPP24</a> 
    </div>

    <?php include_once 'templates/footer.phtml' ?>
    <?php include_once 'templates/javascript.phtml' ?>
  </body>
</html>
