<div class="grid-container">
    <div class="grid-x grid-padding-x">
        <div class="large-3 medium-2 cell"></div>
        <div class="large-6 medium-8 cell">
            <form action="<?=App::config('url')?>workorder/action" method="post">
                <fieldset>
                    <legend>
                        <h4>Work order details</h4>
                    </legend>
                        <p><strong>Client</strong></p>
                        <input type="text" id="searchClient" placeholder="Search client">
                        <p><?=$entity->firstname ?> <?=$entity->lastname ?> <?=$entity->company ?></p>
                    <hr/>
                        <p><strong>Device</strong></p>
                        <input type="text" id="searchDevice" placeholder="Search device">
                        <p><?=$entity->manufacturer ?> <?=$entity->model ?> <?=$entity->serialnum ?></p>
                    <hr/>
                        <p><strong>Workshop</strong></p>
                        <label for="malfunction">Malfunction</label>
                        <textarea rows="5" cols="80" name="malfunction" id="malfunction">
                        </textarea>

                        <input type="hidden" name="frontdesk_id" id="frontdesk_id" value="<?php echo ($entity->workorder_id!=0) ? $entity->frontdesk_id : $_SESSION['authorized']->employee_id ; ?>">
                        <input type="hidden" name="client_id" id="client_id" value="<?=$entity->client_id?>">
                        <input type="hidden" name="device_id" id="device_id" value="<?=$entity->device_id?>">
                        <input type="hidden" name="workorder_id" id="workorder_id" value="<?=$entity->workorder_id?>">
                        
                    <div class="grid-x grid-padding-x">
                        <div class="large-4 medium-4 small-4">
                            <a class="alert button expanded" href="<?=App::config('url')?>workorder/index"><<<   Abort</a>
                        </div>
                        <div class="large-8 medium-8 small-8">
                            <input type="submit" class="button expanded" value="<?=$action?>">
                        </div>
                    </div>
                    <hr/>
                    <p style="color: red"><?=$message?></p>
                </fieldset>
            </form>
        </div>
        <div class="large-3 medium-2 cell"></div>
    </div>
</div>
<pre>
    <?php print_r($entity);?>
    <?php print_r($_SESSION);?>
    <?php print_r($_POST);?>
</pre>