<div class="grid-x">
    <div class="large-8 medium-8 cell">
        <h1 style="font-size: 2rem">Work orders</h1>
    </div>
    <div class="large-3 medium-3 cell">
        <form action="<?=App::config('url')?>workorder/index" method="get">
            <input type="text" name="cond"
            placeholder="Search by client, device, reparman or status"
            value="<?=$cond?>"/>
        </form>
    </div>
    <div class="large-1 medium-1 cell" style="text-align: right">
        <a href="<?=App::config('url')?>workorder/details">
            <i title="Add work order" class="fas fa-2x fa-folder-plus"></i>
        </a>
    </div>
</div>
<table id="tabletemp">
  <thead>
    <tr>
      <th>No.</th>
      <th>Client</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Repairman</th>
      <th>Status</th>            
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($entity as $e): ?>
      <tr>
        <td><?=$e->workorder_id?></td>
        <td><?=$e->firstname?> <?=$e->lastname?> <?=$e->company?></td>
        <td><?=$e->manufacturer?></td>
        <td><?=$e->model?></td>
        <td><?php echo ($e->repairman_id==$e->frontdesk_id) ? '' :$e->repairman_firstname;?></td>
        <td><?=$e->status_name?></td>
        <td>
          <a href="<?=App::config('url')?>workorder/details/<?=$e->workorder_id?>">
            <i title="Edit work order No. <?=$e->workorder_id?>" class="fas fa-2x fa-pen-square"></i>
          </a>
          <a onclick="return confirm('Are you sure you want to delete work order No. <?=$e->workorder_id?>?')" 
            href="<?=App::config('url')?>workorder/delete/<?=$e->workorder_id?>">
            <i style="color:red; margin-left:20px" title="Delete work order No. <?=$e->workorder_id?>"
             class="fas fa-2x fa-minus-square"></i>
          </a>
          <a data-open="details<?=$e->workorder_id?>"><i style="margin-left:20px" 
          title="Details for work order No. <?=$e->workorder_id?>" class="fas fa-2x fa-info"></i></a>
        </td>
      </tr>
      <div class="large reveal" id="details<?=$e->workorder_id?>" data-reveal>
      <h3>Work order No. <?=$e->workorder_id?></h3>
      <hr/>
        <div class="grid-x">
          <div class="large-4 medium-4 cell">
            <h4>Client</h4>
            <hr/>
            <ul>
              <li>
                Client ID: <?=$e->client_id?>
              </li>
              <li>
                Firstname: <?=$e->firstname?>
              </li>
              <li>
                Lastname: <?=$e->lastname?>
              </li>
              <li>
                Company: <?=$e->company?>
              </li>
              <li>
                Phone: <?=$e->phonenum?>
              </li>
              <li>
                E-mail: <?=$e->email?>
              </li>
            </ul>
          </div>
          <div class="large-4 medium-4 cell">
            <h4>Device</h4>
            <hr/>
            <ul>
              <li>
                Device ID: <?=$e->device_id?>
              </li>
              <li>
                Receive date: <?php echo date('Y-m-d',strtotime($e->receive_date));?>
              </li>
              <li>
                Manufacturer: <?=$e->manufacturer?>
              </li>
              <li>
                Model: <?=$e->model?>
              </li>
              <li>
                Serial number: <?=$e->serialnum?>
              </li>
              <li>
                Malfunction: <?=$e->malfunction?>
              </li>
            </ul>
          </div>
          <div class="large-4 medium-4 cell">
            <h4>Workshop</h4>
            <hr/>
            <ul>
              <li>
                Frontdesk: <?=$e->frontdesk_firstname?>
              </li>
              <li>
                Repairman: <?php echo ($e->repairman_id==$e->frontdesk_id) ? '' :$e->repairman_firstname;?>
              </li>
              <li>
                Status: <?=$e->status_name?>
              </li>
              <li>
                Work done: <?=$e->work_done?>
              </li>
              <li>
                Repair date: <?php echo date('Y-m-d',strtotime($e->repair_date));?>
              </li>
              <li>
                Query ID: <?=$e->query_id?>
              </li>
            </ul>
          </div>
        </div>
        <hr/>
        <div style="text-align:center">
        <a href="<?=App::config('url')?>workorder/details/<?=$e->workorder_id?>">
            <i title="Edit work order No. <?=$e->workorder_id?>" class="fas fa-2x fa-pen-square"></i>
          </a>
          <a onclick="return confirm('Are you sure you want to delete work order No. <?=$e->workorder_id?>?')" 
            href="<?=App::config('url')?>workorder/delete/<?=$e->workorder_id?>">
            <i style="color:red; margin-left:20px" title="Delete work order No. <?=$e->workorder_id?>"
             class="fas fa-2x fa-minus-square"></i>
          </a>
        </div>
        <hr/>
        <button class="close-button" data-close aria-label="Close reveal" type="button">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <?php endforeach;?>
  </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
  <li class="pagination-first">
        <a href="<?=App::config('url')?>workorder/index?cond=<?=$cond?>&page=1" aria-label="First page">
        First <span class="show-for-sr">page</span></a>
    </li>
    <li class="pagination-previous">
        <a href="<?=App::config('url')?>workorder/index?cond=<?=$cond?>&page=
        <?php echo $page-1;?>" aria-label="Previous page">
        Previous <span class="show-for-sr">page</span></a>
    </li>
    <li class="current"><span class="show-for-sr">You're on page</span>
        <?=$page?>/<?=$pageTotal?>
    </li>
    <li class="pagination-next"><a href="<?=App::config('url')?>workorder/index?cond=<?=$cond?>&page=
        <?php echo $page+1;?>" aria-label="Next page">
        Next <span class="show-for-sr">page</span></a>
    </li>
    <li class="pagination-last"><a href="<?=App::config('url')?>workorder/index?cond=<?=$cond?>&page=
        <?php echo $pageTotal;?>" aria-label="Last page">
        Last <span class="show-for-sr">page</span></a>
    </li>
  </ul>
</nav>