<div class="grid-x">
    <div class="large-8 medium-8 cell">
        <h1 style="font-size: 2rem">Employees</h1>
    </div>
    <div class="large-3 medium-3 cell">
        <form action="<?=App::config('url')?>employee/index" method="get">
            <input type="text" name="cond"
            placeholder="Search by frstname, lastname, role"
            value="<?=$cond?>"/>
        </form>
    </div>
    <div class="large-1 medium-1 cell" style="text-align: right">
        <a href="<?=App::config('url')?>employee/details">
            <i title="Add employee" class="fas fa-2x fa-user-plus"></i>
        </a>
    </div>
</div>
<table id="tabletemp">
    <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Phonenumber</th>
            <th>E-mail</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($employee as $e): ?>
            <tr>
                <td><?=$e->firstname?></td>
                <td><?=$e->lastname?></td>
                <td><?=$e->phonenum?></td>
                <td><?=$e->email?></td>
                <td><?=$e->employee_role?></td>
                <td>
                    <a href="<?=App::config('url')?>employee/details/<?=$e->employee_id?>">
                        <i title="Edit &quot;<?=$e->firstname?> <?=$e->lastname?>&quot;" class="fas fa-2x fa-pen-square"></i>
                    </a>
                    <?php if ($e->workorder==0): ?>
                        <a onclick="return confirm('Are you sure you want to delete &quot;<?=$e->firstname?> <?=$e->lastname?>&quot;')" 
                        href="<?=App::config('url')?>employee/delete/<?=$e->employee_id?>">
                            <i style="color:red; margin-left:20px" title="Delete &quot;<?=$e->firstname?> <?=$e->lastname?>&quot;"
                             class="fas fa-2x fa-minus-square"></i>
                        </a>
                    <?php else: ?>
                            <i style="color:grey; margin-left:20px" title="&quot;<?=$e->firstname?> <?=$e->lastname?>&quot; can not be deleted" 
                            class="fas fa-2x fa-minus-square"></i>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous disabled">Previous</li>
    <li class="current"><span class="show-for-sr">You're on page</span>
        <?=$page?>/<?=$pageTotal?>
    </li>
    <li class="pagination-next"><a href="#" aria-label="Next page">Next</a></li>
  </ul>
</nav>