<div class="grid-x">
    <div class="large-6 cell">
        <h1 style="font-size: 2rem">Employees</h1>
    </div>
    <div class="large-6 cell" style="text-align: right">
        <a href="<?=App::config('url')?>employee/new">
            <i title="Add employee" class="fas fa-2x fa-user-plus"></i>
        </a>
    </div>
</div>
<table>
    <thead>
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Phonenumber</th>
            <th>E-mail</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($employee as $e): ?>
            <tr>
                <td><?=$e->firstname?></td>
                <td><?=$e->lastname?></td>
                <td><?=$e->phonenum?></td>
                <td><?=$e->email?></td>
                <td><?=$e->employee_role?></td>
                <td>
                    <a href="<?=App::config('url')?>employee/edit/<?=$e->employee_id?>">
                        <i title="Edit" class="fas fa-2x fa-pen-square"></i>
                    </a>
                    <?php if ($e->workorder==0): ?>
                        <a href="<?=App::config('url')?>employee/delete/<?=$e->employee_id?>">
                            <i style="color:red" title="Delete" class="fas fa-2x fa-minus-square"></i>
                        </a>
                    <?php else: ?>
                            <i style="color:grey" title="Can not be deleted" class="fas fa-2x fa-minus-square"></i>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>