<div class="grid-x">
    <div class="large-8 medium-8 cell">
        <h1 style="font-size: 2rem">Clients</h1>
    </div>
    <div class="large-3 medium-3 cell">
        <form action="<?=App::config('url')?>client/index" method="get">
            <input type="text" name="cond"
            placeholder="Search by firstname, lastname or company"
            value="<?=$cond?>"/>
        </form>
    </div>
    <div class="large-1 medium-1 cell" style="text-align: right">
        <a href="<?=App::config('url')?>client/details">
            <i title="Add client" class="fas fa-2x fa-user-plus"></i>
        </a>
    </div>
</div>
<pre>
    <?php print_r($client); ?>
</pre>
<table id="tabletemp">
    <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Company</th>
            <th>Phonenumber</th>
            <th>E-mail</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($client as $c): ?>
            <tr>
                <td><?=$c->firstname?></td>
                <td><?=$c->lastname?></td>
                <td><?=$c->company?></td>
                <td><?=$c->phonenum?></td>
                <td><?=$c->email?></td>
                <td>
                    <a href="<?=App::config('url')?>client/details/<?=$c->client_id?>">
                        <i title="Edit &quot;<?=$c->firstname?> <?=$c->lastname?>&quot;" class="fas fa-2x fa-pen-square"></i>
                    </a>
                    <?php if ($c->device==0): ?>
                        <a onclick="return confirm('Are you sure you want to delete &quot;<?=$c->firstname?> <?=$c->lastname?>&quot;')" 
                        href="<?=App::config('url')?>client/delete/<?=$c->client_id?>">
                            <i style="color:red; margin-left:20px" title="Delete &quot;<?=$c->firstname?> <?=$c->lastname?>&quot;"
                             class="fas fa-2x fa-minus-square"></i>
                        </a>
                    <?php else: ?>
                            <i style="color:grey; margin-left:20px" title="&quot;<?=$c->firstname?> <?=$c->lastname?>&quot; can not be deleted" 
                            class="fas fa-2x fa-minus-square"></i>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
  <li class="pagination-first">
        <a href="<?=App::config('url')?>client/index?cond=<?=$cond?>&page=1" aria-label="First page">
        First <span class="show-for-sr">page</span></a>
    </li>
    <li class="pagination-previous">
        <a href="<?=App::config('url')?>client/index?cond=<?=$cond?>&page=
        <?php echo $page-1;?>" aria-label="Previous page">
        Previous <span class="show-for-sr">page</span></a>
    </li>
    <li class="current"><span class="show-for-sr">You're on page</span>
        <?=$page?>/<?=$pageTotal?>
    </li>
    <li class="pagination-next"><a href="<?=App::config('url')?>client/index?cond=<?=$cond?>&page=
        <?php echo $page+1;?>" aria-label="Next page">
        Next <span class="show-for-sr">page</span></a>
    </li>
    <li class="pagination-last"><a href="<?=App::config('url')?>client/index?cond=<?=$cond?>&page=
        <?php echo $pageTotal;?>" aria-label="Last page">
        Last <span class="show-for-sr">page</span></a>
    </li>
  </ul>
</nav>