<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title"><?=App::config('titleApp')?></div>
</div>



<div class="contain-to-grid fixed">
    <div class="top-bar" id="example-menu">
        <div class="top-bar-left">
            <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text"><?=App::config('titleApp')?></li>
            <li><a href="<?=App::config('url')?>">Home</a></li>
            <li class="has-submenu">
                <a href="#0">One</a>
                <ul class="submenu menu vertical" data-submenu>
                <li><a href="#0">One</a></li>
                <li><a href="#0">Two</a></li>
                <li><a href="#0">Three</a></li>
                </ul>
            </li>
            <li><a href="#0">Two</a></li>
            <li><a href="#0">Three</a></li>
            </ul>
        </div>
        <div class="top-bar-right">
            <ul class="menu">
            <li><a href="<?=App::config('url')?>login/index">Login</a></li>
            </ul>
        </div>
    </div>
</div>