<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
        <div class="grid-container">
            <div class="grid-x grid-padding-x">
                <ul class="dropdown menu" data-dropdown-menu>
                <li class="menu-text">Site Title</li>
                <li>
                    <a href="#0">One</a>
                    <ul class="submenu menu vertical" data-submenu>
                    <li><a href="#0">One</a></li>
                    <li><a href="#0">Two</a></li>
                    <li><a href="#0">Three</a></li>
                    </ul>
                </li>
                <li><a href="#0">Two</a></li>
                <li><a href="#0">Three</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>