<div class="grid-x">
    <div class="large-8 medium-8 cell">
        <h1 style="font-size: 2rem">Devices</h1>
    </div>
    <div class="large-3 medium-3 cell">
        <form action="<?=App::config('url')?>device/index" method="get">
            <input type="text" name="cond"
            placeholder="Search by Client, manufacturer or model"
            value="<?=$cond?>"/>
        </form>
    </div>
    <div class="large-1 medium-1 cell" style="text-align: right">
        <a href="<?=App::config('url')?>device/details">
            <i title="Add device" class="fas fa-2x fa-folder-plus"></i>
        </a>
    </div>
</div>
<table class="table-expand" id="tabletemp">
  <thead>
    <tr class="table-expand-row">
      <th>Client</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($entity as $e): ?>
      <tr class="table-expand-row" data-open-details>
        <td><?=$e->firstname?> <?=$e->lastname?> <?=$e->company?></td>
        <td><?=$e->manufacturer?></td>
        <td><?=$e->model?></td>
        <td>
          <a href="<?=App::config('url')?>device/details/<?=$e->device_id?>">
            <i title="Edit &quot;<?=$e->manufacturer?> <?=$e->model?>&quot;" class="fas fa-2x fa-pen-square"></i>
          </a>
          <?php if ($e->workorder==0): ?>
          <a onclick="return confirm('Are you sure you want to delete &quot;<?=$e->manufacturer?> <?=$e->model?>&quot;')" 
            href="<?=App::config('url')?>device/delete/<?=$e->device_id?>">
            <i style="color:red; margin-left:20px" title="Delete &quot;<?=$e->manufacturer?> <?=$e->model?>&quot;"
             class="fas fa-2x fa-minus-square"></i>
          </a>
          <?php else: ?>
          <i style="color:grey; margin-left:20px" title="&quot;<?=$e->manufacturer?> <?=$e->model?>&quot; can not be deleted becouse it has a workored" 
             class="fas fa-2x fa-minus-square"></i>
          <?php endif; ?>
        </td>
      </tr>
      <tr class="table-expand-row-content">
        <td class="table-expand-row-nested">Phone number: <?=$e->phonenum?></td>
        <td class="table-expand-row-nested">E_mail: <?=$e->email?></td>
      </tr>
    <?php endforeach;?>
  </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous">
        <a href="<?=App::config('url')?>employee/index?cond=<?=$cond?>&page=
        <?php echo $page-1;?>" aria-label="Previous page">
        Previous <span class="show-for-sr">page</span></a>
    </li>
    <li class="current"><span class="show-for-sr">You're on page</span>
        <?=$page?>/<?=$pageTotal?>
    </li>
    <li class="pagination-next"><a href="<?=App::config('url')?>employee/index?cond=<?=$cond?>&page=
        <?php echo $page+1;?>" aria-label="Next page">
        Next <span class="show-for-sr">page</span></a>
    </li>
  </ul>
</nav>